apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microtodo-prod
resources:
  - ../../topology
patches:
  - target: {kind: ConfigMap, name: log-message-processor-config}
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata: {name: log-message-processor-config}
      data:
        REDIS_HOST: redis
images:
  - name: log-message-processor
    newName: pendingacr.azurecr.io/pending-t131/logmsgproc
    digest: sha256:17c5848722fe9bc5a7daf618418008e39ea8077a75dca0ed1c7e5a755bcdfc51
