apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
labels:
  - includeSelectors: false
    pairs: {microtodosuite.io/topology: economical}
patches:
  - target: {kind: Deployment, name: log-message-processor}
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata: {name: log-message-processor}
      spec:
        template:
          metadata:
            annotations: {sidecar.istio.io/inject: "false"}
