apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microtodo-staging
resources: [../../topology]
replicas: [{name: todos-api, count: 1}]
patches:
  - target: {kind: ConfigMap, name: todos-api}
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata: {name: todos-api}
      data:
        REDIS_HOST: redis
  - target: {kind: Deployment, name: todos-api}
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata: {name: todos-api}
      spec:
        template:
          spec:
            containers:
              - name: todos-api
                resources:
                  requests: {cpu: 50m, memory: 64Mi}
                  limits: {cpu: 250m, memory: 256Mi}
images:
  - name: todos-api
    newName: 995253610162.dkr.ecr.us-east-1.amazonaws.com/microtodosuite/todos-api
    digest: sha256:80367c2b7bcd15f12a5308e2af06b449178a1c91aea095d137b963dcf10d6627
