apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microtodo-local
resources: [../../base]
components: [../../components/topology-economical]
replicas: [{name: log-message-processor, count: 1}]
patches:
  - target: {kind: Deployment, name: log-message-processor}
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata: {name: log-message-processor}
      spec:
        template:
          metadata:
            annotations: {policy.microtodosuite.io/baseline: kyverno-v1}
          spec:
            containers:
              - name: log-message-processor
                resources:
                  requests: {cpu: 50m, memory: 64Mi}
                  limits: {cpu: 250m, memory: 256Mi}
images:
  - name: log-message-processor
    newName: localhost:5001/log-message-processor
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
