apiVersion: v1
kind: ResourceQuota
metadata:
  name: environment-budget
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hard:
    requests.cpu: 500m
    limits.cpu: 1500m
    requests.memory: 640Mi
    limits.memory: 2Gi
    pods: "14"
