apiVersion: v1
kind: ResourceQuota
metadata:
  name: environment-budget
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hard:
    requests.cpu: 625m
    limits.cpu: 2700m
    requests.memory: 1Gi
    limits.memory: 2816Mi
    pods: "14"
