apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microtodo-demo
resources: [../../topology]
replicas:
  - name: users-api
    count: 1
patches:
  - target: {kind: Deployment, name: users-api}
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata: {name: users-api}
      spec:
        template:
          spec:
            containers:
              - name: users-api
                resources:
                  requests: {cpu: 150m, memory: 256Mi}
                  limits: {cpu: 500m, memory: 512Mi}
images:
  - name: users-api
    newName: 376784708420.dkr.ecr.us-east-1.amazonaws.com/lex-mts-shd-ecr-usersapi
    digest: sha256:0dcbc4f39b535b01aa08dceb4201c5831b75446f8f1821ddb22512c53a4b4849
