apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microtodo-prod
resources:
  - ../../topology
images:
  - name: frontend
    newName: pendingacr.azurecr.io/pending-t131/frontend
    digest: sha256:5fe218db17bb8d71d00458c44d8a88e9d7c9875f7e5a4cfee980eef45de0e728
  - name: nginx/nginx-prometheus-exporter
    newName: pendingacr.azurecr.io/microtodosuite/platform/nginx-prometheus-exporter
    digest: sha256:85666e7fde7e253f1c6d978f9a961245df4c9cdb7677e1866d9bb28e8f9ee41d
