apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-jwt
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/replace-environment-jwt-reader
automountServiceAccountToken: false
