apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-api-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-secrets-manager
  target:
    name: auth-api-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: replace/environment/auth-api-secrets
