apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-key-vault
  namespace: microtodo-prod
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://pendingt125vault.vault.azure.net
      serviceAccountRef:
        name: external-secrets-jwt
