apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../azure]
components: [../../../components/aks-acr-images]
patches:
  - target: {group: monitoring.coreos.com, version: v1, kind: Prometheus, name: k8s}
    patch: |-
      - op: add
        path: /spec/externalLabels
        value:
          cluster: pending-aks-dr
          environment: prod
  - target:
      group: monitoring.coreos.com
      version: v1
      kind: ServiceMonitor
      name: '^(auth-api|todos-api|users-api|frontend|log-message-processor)$'
    patch: |-
      - op: replace
        path: /spec/namespaceSelector/matchNames
        value: [microtodo-prod]
  - target: {group: external-secrets.io, version: v1, kind: ExternalSecret, name: alertmanager-slack-webhook}
    patch: |-
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: pending-alertmanager-slack-webhook
