apiVersion: v1
kind: Namespace
metadata:
  name: chaos-mesh
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: chaos-mesh
    app.kubernetes.io/part-of: microtodosuite-platform
