apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microtodo-dev
resources: [../../topology]
replicas:
  - name: users-api
    count: 1
patches:
  - target: {kind: Deployment, name: users-api}
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata: {name: users-api}
      spec:
        template:
          spec:
            containers:
              - name: users-api
                resources:
                  requests: {cpu: 150m, memory: 256Mi}
                  limits: {cpu: 500m, memory: 512Mi}
images:
  - name: users-api
    newName: 575172595729.dkr.ecr.us-east-1.amazonaws.com/lex-mts-shd-ecr-usersapi
    digest: sha256:8633f1b7b31a96c5e602b98416cf8ae46385d92d4cacd0d2b8805bd0a8cf9b9a
