apiVersion: v1
kind: Service
metadata:
  name: auth-api-canary
  labels:
    app.kubernetes.io/name: auth-api
    app.kubernetes.io/part-of: microtodosuite
    app.kubernetes.io/component: business-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: auth-api
    app.kubernetes.io/part-of: microtodosuite
    app.kubernetes.io/component: business-service
  ports:
    - name: http
      port: 8000
      targetPort: http
