apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../../../../elasticsearch]
components: [../../../components/aks-acr-images]
patches:
  - target: {group: elasticsearch.k8s.elastic.co, version: v1, kind: Elasticsearch, name: platform}
    patch: |-
      - op: replace
        path: /spec/nodeSets/0/volumeClaimTemplates/0/spec/storageClassName
        value: managed-csi
