apiVersion: v1
kind: ResourceQuota
metadata:
  name: environment-budget
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hard:
    requests.cpu: 550m
    limits.cpu: 2300m
    requests.memory: 896Mi
    limits.memory: 2304Mi
    pods: "12"
