apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microtodo-prod

resources:
  - ../base
  - namespace.yaml
  - resourcequota.yaml
  - rolebinding.yaml

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: frontend
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: eco.microtodosuite.online
      - op: replace
        path: /spec/tls/0/hosts/0
        value: eco.microtodosuite.online
  - target:
      version: v1
      kind: ServiceAccount
      name: external-secrets-jwt
    patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: external-secrets-jwt
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::575172595729:role/lex-mts-eco-role-jwtprd
  - target:
      group: external-secrets.io
      version: v1
      kind: ExternalSecret
      name: auth-api-secrets
    patch: |-
      apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      metadata:
        name: auth-api-secrets
      spec:
        data:
          - secretKey: JWT_SECRET
            remoteRef:
              key: lex-mts-eco-sm-jwtprd
