apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microtodo-prod

resources:
  - ../base
  - namespace.yaml
  - resourcequota.yaml
  - rolebinding.yaml

patches:
  - target:
      version: v1
      kind: ServiceAccount
      name: external-secrets-jwt
    patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: external-secrets-jwt
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::995253610162:role/microtodosuite-prod-jwt-reader
  - target:
      group: external-secrets.io
      version: v1
      kind: ExternalSecret
      name: auth-api-secrets
    patch: |-
      apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      metadata:
        name: auth-api-secrets
      spec:
        data:
          - secretKey: JWT_SECRET
            remoteRef:
              key: microtodosuite/prod/auth-api-secrets
