apiVersion: v1
kind: Namespace
metadata:
  name: microtodo-prod
  labels:
    microtodosuite.io/environment: prod
    microtodosuite.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
