apiVersion: v1
kind: ResourceQuota
metadata:
  name: environment-budget
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hard:
    requests.cpu: 700m
    limits.cpu: "3"
    requests.memory: 1152Mi
    limits.memory: 3Gi
    pods: "18"
