apiVersion: v1
kind: ResourceQuota
metadata:
  name: environment-budget
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hard:
    requests.cpu: 650m
    limits.cpu: "2"
    requests.memory: 896Mi
    limits.memory: 3Gi
    pods: "18"
