apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-default-deny
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-allow-business-services
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: redis
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              microtodosuite.io/environment: "true"
          podSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - todos-api
                  - log-message-processor
      ports:
        - protocol: TCP
          port: 6379
