apiVersion: v1
kind: ServiceAccount
metadata:
  name: sonarqube
  namespace: sonarqube
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sonarqube-postgres
  namespace: sonarqube
automountServiceAccountToken: false
