apiVersion: v1
kind: Namespace
metadata:
  name: opencost
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: opencost
    app.kubernetes.io/part-of: microtodosuite-platform
