apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microtodo-prod
resources: [../../topology]
components: [../../../../components/strategy-canary]
patches:
  - target: {kind: Deployment, name: frontend}
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata: {name: frontend}
      spec:
        replicas: 0
        template:
          metadata:
            annotations:
              release-evidence.microtodosuite.io/exercise: canary-health-gate-v1
          spec:
            containers:
              - name: frontend
                resources:
                  requests: {cpu: 25m, memory: 32Mi}
                  limits: {cpu: 100m, memory: 128Mi}
images:
  - name: frontend
    newName: 575172595729.dkr.ecr.us-east-1.amazonaws.com/lex-mts-shd-ecr-frontend
    digest: sha256:ff9f348fe90afc3438c77b29aa6a61595dd6733b4c9975a4e4e3f2656e814b85
