apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microtodo-prod
resources:
  - ../../topology
images:
  - name: auth-api
    newName: pendingacr.azurecr.io/pending-t131/authapi
    digest: sha256:04af9a416d532184bfd98bc73c77f936138f861572eec0fdbf5ecb6aae76189d
