apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microtodo-dev
resources: [../../topology]
replicas: [{name: frontend, count: 1}]
patches:
  - target: {kind: Deployment, name: frontend}
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata: {name: frontend}
      spec:
        template:
          spec:
            containers:
              - name: frontend
                resources:
                  requests: {cpu: 25m, memory: 32Mi}
                  limits: {cpu: 100m, memory: 128Mi}
images:
  - name: frontend
    newName: 995253610162.dkr.ecr.us-east-1.amazonaws.com/microtodosuite/frontend
    digest: sha256:6b220d2edfa842393e1fb1118ec7c7c81636cce72c0307b9ec77e9c85a2efeaa
