apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microtodo-dev
resources: [../../topology]
replicas:
  - name: users-api
    count: 1
patches:
  - target: {kind: Deployment, name: users-api}
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata: {name: users-api}
      spec:
        template:
          spec:
            containers:
              - name: users-api
                resources:
                  requests: {cpu: 150m, memory: 256Mi}
                  limits: {cpu: 500m, memory: 512Mi}
images:
  - name: users-api
    newName: REGISTRY_PLACEHOLDER/users-api
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
