apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microtodo-dev
resources: [../../topology]
replicas:
  - name: users-api
    count: 1
patches:
  - target: {kind: Deployment, name: users-api}
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata: {name: users-api}
      spec:
        template:
          spec:
            containers:
              - name: users-api
                resources:
                  requests: {cpu: 150m, memory: 256Mi}
                  limits: {cpu: 500m, memory: 512Mi}
images:
  - name: users-api
    newName: 995253610162.dkr.ecr.us-east-1.amazonaws.com/microtodosuite/users-api
    digest: sha256:afa8232041222cb40b87895d1acee82ab19dcca9b7d6d5030154dd591e132f40
