apiVersion: v1
kind: Namespace
metadata:
  name: microtodo-dev
  labels:
    microtodosuite.io/environment: dev
    microtodosuite.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
