apiVersion: v1
kind: ResourceQuota
metadata:
  name: environment-budget
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hard:
    requests.cpu: 400m
    limits.cpu: 1200m
    requests.memory: 512Mi
    limits.memory: 1536Mi
    pods: "12"
